services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: php -S 0.0.0.0:8000 -t public
