<?php

namespace ContainerPuAgxBc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PbkikoxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pbkikox' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pbkikox'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cloudinary' => ['privates', 'App\\Service\\CloudinaryUploader', 'getCloudinaryUploaderService', true],
        ], [
            'cloudinary' => 'App\\Service\\CloudinaryUploader',
        ]);
    }
}
