<?php

namespace ContainerPuAgxBc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BzVWI0QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BzVWI0Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BzVWI0Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'firebase' => ['privates', 'App\\Service\\FirebaseService', 'getFirebaseServiceService', true],
        ], [
            'firebase' => 'App\\Service\\FirebaseService',
        ]);
    }
}
