<?php

namespace ContainerPuAgxBc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFirebaseServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FirebaseService' shared autowired service.
     *
     * @return \App\Service\FirebaseService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FirebaseService.php';

        return $container->privates['App\\Service\\FirebaseService'] = new \App\Service\FirebaseService((\dirname(__DIR__, 4).'/config/firebase/symfony07-firebase-adminsdk-fbsvc-7148aaa659.json'), 'https://symfony07-default-rtdb.firebaseio.com');
    }
}
