<?php

namespace ContainerPuAgxBc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BzVWI0Q.App\Controller\FrontController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BzVWI0Q.App\\Controller\\FrontController::index()'] = ($container->privates['.service_locator.BzVWI0Q'] ?? $container->load('get_ServiceLocator_BzVWI0QService'))->withContext('App\\Controller\\FrontController::index()', $container);
    }
}
