<?php

namespace ContainerPuAgxBc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GalleryController' shared autowired service.
     *
     * @return \App\Controller\GalleryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'GalleryController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FirebaseService.php';

        $container->services['App\\Controller\\GalleryController'] = $instance = new \App\Controller\GalleryController(($container->privates['App\\Service\\FirebaseService'] ??= new \App\Service\FirebaseService((\dirname(__DIR__, 4).'/config/firebase/symfony07-firebase-adminsdk-fbsvc-7148aaa659.json'), 'https://symfony07-default-rtdb.firebaseio.com')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\GalleryController', $container));

        return $instance;
    }
}
