<?php

namespace ContainerPuAgxBc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuFirebaseControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8XAM6wv.App\Controller\MenuFirebaseController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8XAM6wv.App\\Controller\\MenuFirebaseController::add()'] = ($container->privates['.service_locator.8XAM6wv'] ?? $container->load('get_ServiceLocator_8XAM6wvService'))->withContext('App\\Controller\\MenuFirebaseController::add()', $container);
    }
}
