<?php

namespace ContainerPuAgxBc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerupdateOrderStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.crd_c_P.App\Controller\OrderController::updateOrderStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.crd_c_P.App\\Controller\\OrderController::updateOrderStatus()'] = ($container->privates['.service_locator.crd_c_P'] ?? $container->load('get_ServiceLocator_CrdCPService'))->withContext('App\\Controller\\OrderController::updateOrderStatus()', $container);
    }
}
